// 1. Crea una funcion que reciba dos numeros y retorne el mayor de los dos
/*
let numUno = 7
let numDos = 7

function encontrarMayor(a, b ){
   if (a > b){
    return a
   }  
   else{
    return b
   }

}  

let resultado = encontrarMayor(numUno, numDos)

console.log(`El numero ${resultado} es mayor `)
*/

// 2. Crea una funcion que reciba un numero y imprima si es par o impar (procedimiento no return) // DUDA 
/*
let numero = 111111111111111111111111111111

function encontrar(numero){
    let residuo = numero % 2
    if (residuo == 0) {
        console.log("Par")
    }
    else {
        console.log("Impar")
    }
}

encontrar(numero)


// 3. Crea una funcion que reciba un string y retorne la cantidad de caracteres

let palabra = "Hola amigos como estan"

function contar(palabras){
    return palabras.length
}

resuladoContar = contar(palabra)

console.log(`La palabra o la oracion contiene ${resuladoContar} caracteres`)

// 4. Crea una funcion que reciba un numero y retorne su cuadrado

let numero = 345

function sacarCuadrado(numero){
    return numero * numero

}

resultado = sacarCuadrado(numero)
console.log(`El cuadrado de ${numero} es de ${resultado}`)
*/


//*-------------------------- NIVEL2----------------------------------

// Crea una funcion que reciba un numero y retorne un true si es positivo y false si es negativo
/*
let numero = 56

function encontrarPositivo(numero){
    return numero > 0

}

let resultado = encontrarPositivo(numero)

console.log(`El numero ${numero} es ${resultado}`)
*/

// crea una funcion que reciba dos numero y retorne true si son iguiales y false si son diferentes
/*
let numeroUno = 23
let numeroDos = 23

function vericarNumeros(a, b){
    return a === b

}

let resultado = vericarNumeros(numeroUno, numeroDos)

console.log(resultado)
*/

// crea una funcion que reciba un string y retorne la primera letra

// let palabra = "Daniel"
// let inicial = 0

// function mostrarLetra(palabra){
//     return palabra[0]
// }

// let resultado = mostrarLetra(palabra)

// console.log(typeof(resultado)) // nos arrgoa un string 


